version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    command: gunicorn helloworld.wsgi:application --bind 0.0.0.0:8000
    # port 8000 is only exposed internally to other Docker services
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: "${PGSQL_IMAGE}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  nginx:
    build: 
      context: ./nginx
      cache_from:
        - "${WEB_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: