name: Django-Docker CI/CD

on: [push]

env:
  WEB_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/django-docker_web:latest
  NGINX_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY) | tr '[:upper:]' '[:lower:]'/django-docker_nginx:latest
  PGSQL_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY) | tr '[:upper:]' '[:lower:]'/postgres:14.5

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Add environment variables to .env.dev
        run: |
          echo "DEBUG=1" >> .env.dev
          echo "SQL_ENGINE=django.db.backends.postgresql" >> .env.dev
          echo "DATABASE=postgres" >> .env.dev
          echo "SECRET_KEY=foo" >> .env.dev
          echo "DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]" >> .env.dev
      - name: Set environment variables
        run: |
          echo "WEB_IMAGE=$(echo ${{env.WEB_IMAGE}} )" >> $GITHUB_ENV
          echo "NGINX_IMAGE=$(echo ${{env.NGINX_IMAGE}} )" >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u MorsoLi --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.WEB_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true
      - name: Build images
        run: |
          docker-compose -f docker-compose.ci.yaml build
      - name: Push images
        run: |
          docker push ${{ env.WEB_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}

